'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _1opener

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''HL1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL1 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL2 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL3 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL4 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL5 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL6 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL7 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL8 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL9 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL10 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL11 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL12 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL13 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL14 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL15 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL16 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL17 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL18 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL19 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL20 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL21 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL22 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL23 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL24 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL25 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL26 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL27 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL28 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL29 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL30 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''HL31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HL31 As Global.System.Web.UI.WebControls.HyperLink
End Class
