<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="p22.aspx.vb" Inherits="asp_practical.p22" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
   <head id="Head1" runat="server">
      <title></title>
   </head>
   <body>
      <form id="form1" runat="server">
         <asp:DetailsView ID="DV1" runat="server" AllowPaging="True" 
            AutoGenerateRows="False" DataSourceID="SDS1" 
            AutoGenerateInsertButton="True" DataKeyNames="id">
            <Fields>
               <asp:BoundField DataField="id" HeaderText="id" SortExpression="id" 
                  ReadOnly="True" />
               <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
            </Fields>
         </asp:DetailsView>
         <br />
         <br />
         <asp:GridView ID="GV1" runat="server" AutoGenerateColumns="False" 
            DataSourceID="SDS1" AutoGenerateEditButton="True" 
            AutoGenerateDeleteButton="True" DataKeyNames="id">
            <Columns>
               <asp:BoundField DataField="id" HeaderText="id" SortExpression="id" 
                  ReadOnly="True" />
               <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
            </Columns>
         </asp:GridView>
         <br />
         <asp:SqlDataSource ID="SDS1" runat="server"
            ConnectionString="<%$ ConnectionStrings:jayConnectionString %>"
            SelectCommand="SELECT * FROM [e5]"
            InsertCommand="INSERT INTO [e5] ([id], [name]) VALUES (@id, @name)"
            UpdateCommand="UPDATE [e5] SET [name] = @name WHERE [id] = @id"
            DeleteCommand="DELETE FROM [e5] WHERE [id] = @id" >
            <DeleteParameters>
               <asp:Parameter Name="id" />
            </DeleteParameters>
            <InsertParameters>
               <asp:Parameter Name="id"  />
               <asp:Parameter Name="name" />
            </InsertParameters>
            <UpdateParameters>
               <asp:Parameter Name="name" />
               <asp:Parameter Name="id" />
            </UpdateParameters>
         </asp:SqlDataSource>
      </form>
   </body>
</html>